spring:
  config:
    # 시크릿 매니저 설정
    import: 'aws-secretsmanager:arn:aws:secretsmanager:us-east-1:393035689023:secret:/secret/prod/weasel-I4AhIF'
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    # mysql 데이터베이스 이용할 때
    url: jdbc:mysql://${HOST}:${PORT}/${DATABASE}
#    username: ${USERNAME}
    username: ${mysql-username}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${local-url}
#    username: ${local-name}
#    password: ${local-pw}
#    driver-class-name: org.h2.Driver

  jpa:
    # mysql 데이터베이스 이용할 때
    database-platform: org.hibernate.dialect.MySQL8Dialect
#    dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    io.awspring.cloud.secretsmanager: DEBUG
    com.amazonaws: DEBUG

cloud:
  aws:
    s3:
      bucket: weasel-images # 버킷 이름
    region:
      static: us-east-1
    secretsmanager: # 테스트
      name: "/secret/prod/weasel"
      region: us-east-1
    stack:
      auto: false
    # credentials:
    #   accessKey: ${accessKey}
    #   secretKey: ${secretKey}
